[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
lambda_runtime = "0.13.0"
tokio = { version = "1", features = ["macros"] }
data-storage = { path = "../data-storage", version = "0.1.0" }


[[bin]]
name = "lambda"
path = "src/main.rs"

